commands:
  test_case_1:
    - command: "reset"
      delay: 1
    - command: "get_version"
    - command: "read_register 0x1234"
      
  test_case_2:
    - command: "set_mode debug"
    - command: "write_register 0x5678 0xFF"
      delay: 0.5
    - command: "read_register 0x5678"
